version: "3.3"
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mjuletter-database.cocpikrk0lh6.ap-northeast-2.rds.amazonaws.com:3306/mjuletter_database
      - SPRING_DATASOURCE_USERNAME=mjuletter
      - SPRING_DATASOURCE_PASSWORD=mjuletter!
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mjuletter_database
    ports:
      - "3306:3306"
